---
title: "Abstract"
author: "J Ted Hillert"
date: "`r Sys.Date()`"
output: word_document
---

```{r setup, include=FALSE}

library(papaja)

papaja::r_refs(file="proposal.bib")

options(knitr.kable.NA="")


```

On the borders of Cherokee National Forest in Tennessee and Pisgah National Forest in North Carolina lie the balds of Carver's Gap - a rare and unique ecosystem subtype that hosts high floral and faunal diversity. These balds are experiencing woody encroachment from the surrounding forest and from blackberry species threatening alteration from a grass bald to a heath bald. In 2020, a survey of the balds of Carver's gap was conducted following 30 years of mowing management. Mowing was shown to reduce the spread of *rubus* species and showed a positive effect on graminoid cover with frequent disturbance. In February of 2022, a low-intensity ground fire burned approximately 9.7 hectares of area on Round bald, the first bald on Carver's Gap. This study surveyed vegetation at the functional level - *rubus*, grass, sedge, rhododendron, fern, forb, moss, rock, and bare ground - using a 1-meter square quadrat divided into 100 equal sized squares. Vegetation type was visually determined in each square to reach 100% cover for each plot. A total of 99 plots were measured along the first four transects reestablished by Stokes and Horton (2022). I examined the vegetation composition post fire and one year post fire at the plot level to determine density of *rubus* and grass species on the bald. Two soil seed bank samples were taken in July of 2022 and January of 2023, the first underwent seedling emergence trial, while the latter will undergo seedling emergence and seed extraction trials. Preliminary analysis of plot level data on *rubus* and grass indicates that a greater percentage of plots containing *rubus* and grass were burned vs unburned. A second vegetation composition survey will be conducted in June of 2023 to examine vegetation composition one year following the fire disturbance. Conclusions from this study can be used to inform managing agencies about the benefits and drawbacks of naturally occurring fire on high elevation treeless meadows.