---
title: "Thesis-Schmesis"
author: "J. Hillert"
date: "`r Sys.Date()`"
output:
  bookdown::html_document2:
    number_sections: false
    toc: yes
    always_allow_html: true
    
bibliography:
- R-packages.bib
- aRticles.bib

csl: ecology.csl

---


```{r setup, include=FALSE}

knitr::opts_chunk$set(message=FALSE,
                      echo=FALSE,
                      warning=FALSE)

library(broom)
library(car)       # Primarily for the Anova() function
library(DescTools) # For the GTest
library(emmeans)
library(FactoMineR)  # provides exploratory mutlivariate methods
library(factoextra)  # Visualize the Results of Multivariate Data Analyses
library(ggfortify)
library(ggplot2)
library(ggpubr)
library(ggrepel)
library(kableExtra)
library(lattice)   # For diagnostic plots of linear models in LME4
library(latex2exp)
library(lme4)      # For linear mixed effects modelling
library(lmerTest)  # To provide P-values for lme4
library(patchwork)
library(purrr)
library(readxl)
library(tidyverse)


papaja::r_refs(file = "schmesis.bib")

options(knitr.kable.NA = "")

set.seed(42)


```

# Import

```{r imports, message=FALSE, warning=FALSE, include=FALSE}

# R/Excel data \/\/
vege<-read_excel("round bald datas/round bald data.xlsx",
                 sheet = "Ground Cover")
view(vege)

# PC-ORD data \/\/
stokall <- read_excel("2020-2022 ordination.xlsx", 
    sheet = "2020all")
stokenvr <- read_excel("2020-2022 ordination.xlsx", 
    sheet = "2020envr")
stokvege <- read_excel("2020-2022 ordination.xlsx", 
    sheet = "2020vege")
tedall <- read_excel("2020-2022 ordination.xlsx", 
    sheet = "2022all")
tedenvr <- read_excel("2020-2022 ordination.xlsx", 
    sheet = "2022envr")
tedvege <- read_excel("2020-2022 ordination.xlsx", 
    sheet = "2022vege")

```

# Boxplots

```{r boxplots, echo=FALSE}

#Rubus
rubus<-ggplot(vege) +
  geom_boxplot(aes(Transect,Rubus))+
  geom_jitter(aes(x=Transect, 
                  y=Rubus, 
                  color=Fire
                  ),
              width=0.3, 
              alpha=0.5, 
              size=4, 
              shape=16)+
  xlab("")+
  theme_classic()

#Grass
grass<-ggplot(vege) +
  geom_boxplot(aes(Transect,"Grass/Oat"))+
  geom_jitter(aes(x=Transect, 
                  y="Grass/Oat", 
                  color=Fire
                  ),
              width=0.3, 
              alpha=0.5, 
              size=4, 
              shape=16)+
  xlab("")+
  theme_classic()

#Sedge
sedge<-ggplot(vege) +
  geom_boxplot(aes(Transect,Sedge))+
  geom_jitter(aes(x=Transect, 
                  y=Sedge, 
                  color=Fire
                  ),
              width=0.3, 
              alpha=0.5, 
              size=4, 
              shape=16)+
  xlab("")+
  theme_classic()

rubus
grass
sedge

```

# lm.modA

```{r vegemod, echo=TRUE}

rubu<-lm(Rubus~Fire,
         data=vege)
aovrubu<-aov(rubu)
ottorubu<-autoplot(aovrubu)
ottorubu

gras<-lm(Grass~Fire,
         data=vege)
aovgras<-aov(gras)
ottogras<-autoplot(aovgras)
ottogras

sedg<-lm(Sedge~Fire,
         data=vege)
aovsedg<-aov(sedg)
ottosedg<-autoplot(aovsedg)
ottosedg

aovrubu
aovgras
aovsedg

```

# tablA_Anova.gras

```{r grascova, echo=FALSE}

#using R-car package
grasmod.out<-Anova(gras)

grasmod.out$'Pr(>F)'<-format.pval(grasmod.out$'Pr(>F)',
                                   eps=0.0001,
                                   digits=4,
                                   na.form=""
)
grasmod.out

grasmod1.cap<-"ANOVA summary for the effect of Fire on Grass species"

#using R-kableExtra package
kbl(grasmod.out,
    align='r',
    digits=c(2,0,2,4),
    caption=grasmod1.cap
    )|>
  kable_classic(full=FALSE)


```

# tablA_Anova.rubu

```{r rubucova, echo=FALSE}

#using R-car package
rubumod.out<-Anova(rubu)

rubumod.out$'Pr(>F)'<-format.pval(rubumod.out$'Pr(>F)',
                                   eps=0.0001,
                                   digits=4,
                                   na.form=""
)
rubumod.out

rubumod1.cap<-"ANOVA summary for the effect of Fire on Rubus species"

#using R-kableExtra package
kbl(rubumod.out,
    align='r',
    digits=c(2,0,2,4),
    caption=rubumod1.cap
    )|>
  kable_classic(full=FALSE)


```

# tablA_Anova.sedg

```{r sedgcova, echo=FALSE}

#using R-car package
sedgmod.out<-Anova(sedg)

sedgmod.out$'Pr(>F)'<-format.pval(sedgmod.out$'Pr(>F)',
                                   eps=0.0001,
                                   digits=4,
                                   na.form=""
)
sedgmod.out

sedgmod1.cap<-"ANOVA summary for the effect of Fire on Sedge species"

#using R-kableExtra package
kbl(sedgmod.out,
    align='r',
    digits=c(2,0,2,4),
    caption=sedgmod1.cap
    )|>
  kable_classic(full=FALSE)


```

# lm.modsB

```{r lm.modB, include=FALSE}

## Rubus

#using @R-base package
rubmod<-lm(Transect~Rubus+Fire,
            data=vege
            )
summary(rubmod)

#using @R-ggfortify package
rubmod<-autoplot(rubmod)



## Grass

#using @R-base package
gramod<-lm(Transect~Grass+Fire,
            data=vege
            )
summary(gramod)

#using @R-ggfortify package
gramod<-autoplot(gramod)



## sedge

#using @R-base package
sedmod<-lm(Transect~Sedge+Fire,
            data=vege
            )
summary(sedmod)

#using @R-ggfortify package
sedmod<-autoplot(sedmod)


rubmod
gramod
sedmod

```

# tablB_Anova.gra

```{r rubcova, echo=FALSE}
#using R-car package
rubmod.out<-glm(rubu)

rubmod.out$'Pr(>F)'<-format.pval(rubmod.out$'Pr(>F)',
                                   eps=0.0001,
                                   digits=4,
                                   na.form=""
)
rubmod.out

rubmod1.cap<-"ANOVA summary for the effect of Fire on Grass species"

ggplot(vege) +
  geom_boxplot(aes(Transect,Grass))+
  geom_jitter(aes(x=Transect, 
                  y=Grass, 
                  color=Fire
                  ),
              width=0.3, 
              alpha=0.5, 
              size=4, 
              shape=16)+
  xlab("")+
  theme_classic()


```

# tablB_Anova.rub

```{r sedcova, echo=FALSE}
#using R-car package
sedmod.out<-glm(sedg)

sedmod.out$'Pr(>F)'<-format.pval(sedmod.out$'Pr(>F)',
                                   eps=0.0001,
                                   digits=4,
                                   na.form=""
)
sedmod.out

sedmod1.cap<-"ANOVA summary for the effect of Fire on Grass species"

ggplot(vege) +
  geom_boxplot(aes(Transect,Grass))+
  geom_jitter(aes(x=Transect, 
                  y=Grass, 
                  color=Fire
                  ),
              width=0.3, 
              alpha=0.5, 
              size=4, 
              shape=16)+
  xlab("")+
  theme_classic()


```

# tablB_Anova.sed

```{r grascova, echo=FALSE}
#using R-car package
gramod.out<-glm(gras)

gramod.out$'Pr(>F)'<-format.pval(gramod.out$'Pr(>F)',
                                   eps=0.0001,
                                   digits=4,
                                   na.form=""
)
gramod.out

gramod1.cap<-"ANOVA summary for the effect of Fire on Grass species"

ggplot(vege) +
  geom_boxplot(aes(Transect,Grass))+
  geom_jitter(aes(x=Transect, 
                  y=Grass, 
                  color=Fire
                  ),
              width=0.3, 
              alpha=0.5, 
              size=4, 
              shape=16)+
  xlab("")+
  theme_classic()


```

