---
title: "Discussion"
author: "J. Ted Hillert"
date: "`r Sys.Date()`"
output:
  #bookdown::html_document2:
  bookdown::word_document2:
  #bookdown::pdf_document2:
    number_sections: false
    toc: yes

bibliography:
- aRticles.bib
   
csl: ecology.csl

---

\newpage

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo=FALSE,
                      message=FALSE,
                      warning=FALSE)


library(kableExtra)
library(latex2exp)
library(pandoc)
library(papaja)


papaja::r_refs(file="discussion.bib")

options(knitr.kable.NA="")


```


# Discussion

The objectives of this study were to examine how the 2022 low intensity ground fire affected the vegetation community compared to the survey conducted by @Stok2022 in 2020. NMDS results indicated that much of the vegetation composition were similar to each other in 2020 and 2022 and in unburned and burned plots in 2022. These results suggest that the fire had little overall effect on the landscape. This is likely due to the fact that the fire did not burn for a long enough period of time nor did it reach a high enough temperature to cause a strong lasting effect. There was a handful of plots that were dissimilar to the main portion of the burned and unburned data points, these were shown to be plots with greater similarity to bare rock, moss, and *Rhododendron* cover types. These plots were also largely unburned and therefore little change was likely to occur in these areas. Analysis of the data using MRPP showed significant differences between burned and unburned plots both years but according to the average distances between burned and unburned plots there was little difference overall. This finding supports the NMDS finding that the fire had little overall effect on the landscape evident from the grouping of plots in much of the same ordination space. These data are in support of the hypothesis that the fire would have little effect on the bald. Further support for this finding comes from Shannons indices, which showed that the 2020 and 2022 vegetation compositions were very similar in diversity and evenness. However, in 2022 alone, the diversity in the unburned plots was greater than the diversity in the burned plots, with burned plots being less even than unburned plots. The dominance curves for 2020 and 2022 showed a similar trend with more evenness in 2020 than in 2022. The dominance curve for 2022 matches up with the finding from Shannons diversity and evenness indices, with more evenness and diversity in the unburned plots. 

A greater number of seeds were extracted from burned versus unburned soil samples indicating the duff layer of unburned plots acts as a filter that prevents seeds from entering the seedbank. Only one type of seed was identified, belonging to *Rubus* species, all other seeds were potentially to small to identify or to rare to be a major part of the seedbank. Results from the seedbank emergence trial showed slightly greater diversity in the unburned plots suggests that fire has a reducing effect on diversity and evenness of the landscape. Likewise it is possible that fire has a reducing effect on the abundance of *Rubus* species on the landscape. Further experimentation with fire is necessary to draw conclusions on the effects of fire. It is important to note that data for the emergence trial were drawn from a small dataset therefore it is likely that these results are not indicative of the true state of the seedbank. 

Fire suppression activities in the 1950's virtually eliminated fire as an ecological process on balds [@Broc2002]. Fire is an important ecological process in prairie and grassland ecosystems as it drives the evolution of the local species to a state of arrested succession [@Broc2002]. The importance of fire in bald ecosystems has been debated with their origins with some believing that prescribed burns are part of what maintained the openness of balds [@Gers1970; @Bard1978]. The use of fire has been suggested for use in conjunction with mowing by @Murd1986, however its use has been limited to this day. There are many factors to consider when using fire as a silvicultural practice on balds, namely the difficulty of maintaining the boundaries of a fire and the threat they pose on the adjacent ecosystems, in this case spruce-fir. Fire can quickly spread across and over the mountaintop owing to the high winds of the area. Should the use of fire be reinstated on balds, then the application must consider the season of the burn, intensity of the burn, length of burn, and frequency of application. It has been suggested by @Broc2002 and @Fynn2004, that dormant season burns are effective against the regeneration of *Rubus* and for the recovery of grass species. It is also necessary for the fire to achieve a high enough intensity to be effective against woody invasion which can be achieved in the drier part of the season [@Smit2010]. Length of burns is necessary to achieve hot enough temperatures such that the heat has the ability to penetrate the ground and potentially desiccate roots and seeds in the soil. Last important point in the use of fire as a silvicultural practice is the frequency of burns, it is necessary to wait an appropriate amount of time between burns to allow fuels to return to the density needed to achieve appropriate fire intensity levels. @Bard1978 suggests a frequency of five years between burns for lower severity burns, while @Smit2010 suggest less than six years between burns to show a lasting effect on woody vegetation and to accumulate fuel loads.

*Rubus* is present across the bald with patches of growth that are prominent over the main vegetation - grass. It is unlikely that fire will be reintroduced as a management practice on Round bald (pers. comm. Gary Kauffman USFS) and therefore some form of management of these patches is necessary. Hand pulling of aboveground vegetation is ineffective as *Rubus* is able to regrow from the smallest fragmented root stock [@Davi1998], likewise it would be extremely labor intensive. Herbicide treatment is out of the question because of the wicking effect into the earth will have unknown effects on the surrounding vegetation, especially rare flora, and could ultimately do more harm than good [@Davi1998]. Grazing was once a popular practice on balds, especially owing to its purported reason for balds existence. However, it has been reported that grazing was attempted on Round bald and other balds but the non-selectivity of grazers caused the practice to be discontinued [@Stok2022] due to negative effects on rare flora. It is therefore likely that track mowing is the most convenient, selective, and safe method for maintaining this bald. However, considering the presence of *Rubus* despite many years of mowing being the prime management tool on these balds, it is likely pertinent to increase the amount of mowing to see any future effects on woody invasion. I suggest mowing a second time earlier in the year before grasses are far above the ground and when *Rubus* species are still canes and a second mow latter in the season before *Rubus* goes to fruit. This would cause the plants to use up more of the energy in their root stores and prevent seeds from making it into the seedbank later in the season. 

Future management efforts should continue to mow on a yearly basis to combat the spread of *Rubus* on Round bald. Managers should also consider the application of small contained fire on dense patches of *Rubus* as a means to combat its spread and limit the negative impacts that fire could impose on rare and endemic flora of the bald. Should the application of fire be completely rejected then a second application of mowing earlier in the year ought to be considered as a means of reducing energy stores of invasive plants. Otherwise management efforts should continue to monitor the vegetation composition of the balds through yearly surveys along the transects used in this study and the study by @Stok2022. This line of research would be key to maintaining the diversity and aesthetic value of the flora of this grass bald and other balds. Further research on the rare plants of grassy balds, particularly Roan Lily (*Lilium grayi*) on Round bald, should be conducted to examine the effects of management on their persistence. Continued management is key to protecting grass balds and their conservation and preservation is essential for the persistence of these dwindling ecosystems, the rare and endemic flora that they host, and their aesthetic value for ecotourism. 




\newpage

# References

