---
title: "Methods, Analysis, and Results"
author: "J. Ted Hillert"
date: "`r Sys.Date()`"
output:
  #bookdown::html_document2:
  bookdown::word_document2:
  #bookdown::pdf_document2:
    number_sections: false
    toc: yes

bibliography:
- aRticles.bib
   
csl: ecology.csl
    
  
---



\newpage

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo=FALSE,
                      message=FALSE,
                      warning=FALSE)


library(kableExtra)
library(latex2exp)
library(pandoc)
library(papaja)


papaja::r_refs(file="methods.bib")

options(knitr.kable.NA="")


```

# METHODS

### Study Site

Round bald is located in the Roan Mountain Massif of the Unaka Mountain range of the Southern Appalachian Mountains, between Carver's Gap and Engine Gap. The Appalachian Trail (AT) bisects the study site into north and south sides of the trail. The site itself is spread across Pisgah National Forest in North Carolina and Cherokee National Forest in Tennessee, at approximately 36.1065077° N and -82.1104007° W. Round bald is considered a grass bald subtype dominated by *Danthonia* and *Carex* species with encroaching patches of *Rubus* species [@NCNHP]. The site is mesic due to high rainfall, frequent fog, and low temperatures. The site is also exposed to drying winds. In 2020, @Stok2022 surveyed the balds of Carver's Gap using methods from @Hame1990 and @Murd1986 to assess the effects of 30 years of management by mowing. The first four transects used in this study are identified in Figure 1. They detailed the vegetation composition of the balds according to vegetation genera, details of which will be described below. In February 2022, a low-intensity ground fire burned roughly 9.7 hectares of aboveground vegetation and was quickly extinguished before it could spread further. The site has otherwise not been burned for several decades [@Murd1986]. This provided an opportunity to examine the changes in vegetation composition following low-intensity ground fire over the following season in June of 2022.

### Field Methods

This study was a repeat survey following the survey conducted by @Stok2022 in 2020. They surveyed Round bald, Grassy Ridge bald, and Jane bald across 12 transects with 226 total plots. In their study they determined percent cover of vegetation using a 1 x 0.5 m^2 PVC quadrat divided into 50 equal sized squares. They measured 1 x 1 m^2 plots starting with the northern half of each plot, followed by the southern half. They assigned each square a dominant type of vegetation to a total of 100% per plot. Vegetation composition focused on a few dominant species (e.g. *Rubus* and *Rhododendron*) and main functional types (e.g. grass, sedge, fern, etc.). In this study I sampled the first four transects established by @Stok2022. I quantified vegetation to genera by functional types; *Rubus*, *Vaccinium*, *Rhododenron*, forb, grass, sedge, moss, rock, or bare ground. These were determined to be the dominant vegetation and main functional species by USFS botanist Gary Kauffman as a method to efficiently survey the balds. I measured the percent coverage of vegetation using a 1-m^2 PVC quadrat divided into 100 equal sized squares. Each square was visually assigned by dominant vegetation genera to equal 100% coverage per plot of aboveground vegetation up to 1-meter in height. A total of 226 plots along 12 transects were sampled in 2020, of these, 52 plots - along the first four transects were in the February 2022 fire - and another 47 plots - along the same transects - were unburned (Figure 1).

### Soil Seed Bank

To examine the effects of the fire on the seed bank, seed bank samples were collected in July 2022. In July 2022, approximately 200 grams of soil were obtained from the top 5 cm of soil at six random plots in one of four categories; over 50% *Rubus*/burned, over 50% *Rubus*/unburned, under 25% *Rubus*/burned, under 25% *Rubus*/unburned. The first - over 50% *Rubus*/burned - describes plots with greater than 50% cover of *Rubus* and burned from the February 2020 fire, followed by greater than 50% *Rubus* and unburned, less than 25% *Rubus* and burned, lastly, less than 25% *Rubus* and unburned. A total of 24 soil seed bank samples were taken, placed in tins, transferred to the greenhouse, then sown in 28x22 cm seedling trays filled with Miracle Gro potting mix to 5 cm depth. An additional six trays were filled with unaltered potting mix which acted as greenhouse controls to rule out contamination. Trays were randomly placed in the greenhouse at ambient temperature and humidity which was measured continuously with a Govee probe (Shenzhen Intellirocks Tech Co. Ltd. - China) - the probe continuously measures temperature, percent relative humidity, dew point, and vapor-pressure-deficit. As seedlings emerged they were identified to genera, recorded, and removed. The seedlings that could not be identified were re-potted until identifiable following @Pric2010. Each month the trays were rotated in random order to equalize growing conditions. In December of 2022, the soil sample trays were placed outside to simulate winter conditions and cold stratify seeds in the seed bank over the next spring. 

A modified soil extraction method from the second soil sample was added in 2023 following @Pric2010 @Abel2013; and @Chiq2018. These authors identify that both methods - seed extraction and seed germination - can provide insight into the potential vegetation community, but a combination of the two provides a more robust estimate of the state of the seed bank. A second set of soil seed bank samples were collected in January of 2023 following the same protocol as the first set. This time, however, two samples were taken from each plot and a total of 76 samples were collected from 36 sites on Round bald. One half of these samples were dried, weighed, and underwent seed extraction. The second set of soil seedbank samples were collected in January 2023  and set in the fridge at 4 °C until March 2023. In March samples were removed from the fridge and set in the greenhouse to thaw and dry. After which each sample was sifted through 4000-micron mesh and then sifted through with jeweler's forceps to locate and count seeds - a total of 34 samples underwent seed extraction. Another 36 samples were placed in one half of 25x50 cm  seedling trays divided down the center, such that each sample was in a 25x25 cm area. To accommodate for space in the greenhouse a total of 15 burned, 15 unburned, and 6 controls samples were sown into eighteen 25x50 cm seedling trays such that one half contained a sample that was burned and the other half had a sample that was unburned.

# Analysis

Differences between the 2020 and 2022 plant communities were analyzed using percent cover vegetation data and conducted in PC-ORD 7 [@PCORD7]. Nonmetric Multidimensional Scaling (NMDS) was used to visualize percent cover of vegetation for unburned and burned plots between 2020 and 2022. NMDS analysis was performed on a matrix of 198 plots - 104 of which were burned and another 94 were unburned - by 10 cover classes. Multi-response permutation procedure (MRPP) was used to test whether vegetation composition differed between plots that were burned and plots that were unburned. Sorensen's distance was calculated from the percent cover data of the 99 total plots.  Shannons diversity index and Shannons evenness index were calculated in Microsoft Excel to further examine the difference between vegetation composition between years and between burned and unburned plots in 2022 [@msexcel]. Dominance curves were calculated in PC-ORD by multiplying the total abundance against the rank order of abundance, and was used to examine the distribution of vegetation by percent cover between years [@PCORD7]. 

Soil seedbank emergence data were combined into one dataset and examined using R studio via one-way t-tests between burned and unburned plots of each vegetation type that grew from sample trays [@rstudio]. Another one-way t-test was used to compare germination between burned and unburned samples. Shannon diversity was conducted using Microsoft Excel on soil sample emergence data to examine the diversity of species that grew from the seedbank in burned and unburned plots [@msexcel]. Shannon evenness index was also used to compare the composition and richness of burned and unburned samples. Seed extraction data was calculated based on amount of seeds per 100g.

# Results

NMDS analysis of burned and unburned data grouped them in much of the same space with most data points overlapping (Figure 2), indicating little difference between burned and unburned vegetation plots. A handful of data points were separated from the major ordination space indicating a difference in vegetation in unburned and burned data points in 2020 and 2022. Analysis of these separated data points indicates greater relation of vegetation to bare rock, moss, and *Rhododendron* species (Figure 2). Analysis of vegetation cover data by MRPP indicated significant differences between burned and unburned plots in both years - 2020 p = 0.00526 and 2022 p = 0.00554. In 2020, the average distance for unburned plots equals 0.6643, while the distance for burned plots was 0.4942. While in 2022, the average distance for unburned plots equals 0.6394 and the average distance in burned plots equals 0.4750. Further analysis with Shannon diversity index indicates the diversity in 2020 and 2022 were very similar - 1.69 versus 1.64, respectively. Likewise Shannon evenness index indicated similar values in 2020 and 2022 - 0.733 versus 0.714, respectively. In 2022 there were differences in Shannons diversity and evenness  for unburned and burned plots - unburned plots had a diversity of 1.78 and an evenness of 0.775, while burned plots had a diversity of 1.36 and an evenness of 0.654. Dominance curves in 2020 versus 2022 indicate a marked increase in *Rubus* species and bare rock cover, and a marked decrease in *Rhododendron* and forb species (Figure 3).

Analysis of seedbank emergence data was conducted using one-way t-tests on vegetation types *Rubus*, grass, and forb species. T-test scores for each were not significant - *Rubus* p-value = 0.5998, grass p-value = 0.7887, and forb p-value = 0.3758. Likewise, t-test score for all seed germination data was not significant (p-value = 0.6492), indicating little difference in vegetation germination between plots that were burned versus plots that were unburned. Shannon diversity scores indicate a different trend, the total diversity in the unburned samples was greater than the diversity in the burned samples, 1.051 versus 0.854 - respectively. Conversely Shannon evenness scores indicate similar evenness between unburned and burned samples, 0.758 versus 0.777 - respectively. Seed extraction data shows a greater number of seeds in burned samples versus unburned samples, 105.48 seeds/100g versus 26.73 seeds/100g - respectively. 

\newpage

# References
