---
title: "Vegetation dynamics following low-intensity ground fire on a rare ecosystem subtype - Grass Bald"
subtitle: "Masters student thesis proposal for Western Carolina University"
author: "J. Ted Carter"
date: "`r Sys.Date()`"
output:
  bookdown::html_document2:
  #bookdown::word_document2:
  #bookdown::pdf_document2:
    number_sections: false
    toc: yes

bibliography:
- aRticles.bib



 #^^ pandoc.exe: Cannot decode byte '\xe2': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream 
 #Error: pandoc document conversion failed with error 1
 #Execution halted
   
csl: ecology.csl
    
  
---



\newpage

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo=FALSE,
                      message=FALSE,
                      warning=FALSE)


library(kableExtra)
library(latex2exp)
library(pandoc)
library(papaja)


papaja::r_refs(file="proposal.bib")

options(knitr.kable.NA="")


```

# INTRODUCTION

## Round Bald

Round bald is located along the borders of North Carolina and Tennessee of the Appalachian Trail. The site is about 20 miles North of Bakersville, North Carolina and about 13 miles South of Roan Mountain, Tennessee. Round bald has been experiencing woody encroachment from invasive species like *Rubus allegheniensis*, *Rubus canadensis*, *Vaccinium spp.*, *Rhododendrom spp.* and saplings from the surrounding spruce-fir forest. These species are causing the bald to shift from a grass bald suptype into a heath bald subtype. Grass balds are defined as the majority of vegetation is either grasses or sedges. Following woody encroahment, This could potentially extirpate a rare ecosystem subtype that provides panoramic vista views of the adjacent mountaintops and hosts a number of rare and endemic species, such as - Roan Lily, *Lilium grayi*. Nearly 40 years ago, @Murd1986 and @Hame1990 examined the vegetation community of Roan Mountain balds when the decision to protect these landscapes started to change. In 2020, following 30 years of mowing management, @Stok2022 re-surveyed plots from @Murd1986 and @Hame1990. In February of 2022, there was a low-intensity ground fire that burned for less than 6 hours and burned approximately 9.7 hectares of Round Bald. Roughly half of the plots that @Stok2022 surveyed on Round Bald along the first four transects were within the fire and the other half - along the same four transects - were outside of the fire boundary.

## History

Upper montane treeless meadows - balds - host high floral diversity, panoramic views of the landscape, and origins hotly debated to this day [@Gers1970; @Murd1986; @Hame1990]. Many speculate that balds were cleared by early settlers for pasturing livestock in the spring and summer seasons [@Lind1979b] - anthropogenic origin. Others believe that they are of a climate-herbivore driven change in the landscape, making it a natural ecosystem [@Weig1995; @Weig2014]. True balds are above 1,400 meters in elevation, while any bald can exist on a rock outcrop above 1,200 meters in elevation [@Gers1970]. Furthermore, true balds occur only in the Southern Blue Ridge Physiographic Province, other balds - apparent balds - are distributed globally with sites in Siberia and Australia, among others. There has been much in the way of bald history in the literature, but data regarding vegetation dynamics following disturbance is scant or focused on other balds. Management of these balds varies by managing agency, type of bald - heath or grass, and proposed origin - whether it was cleared, grazed, burned, or some combination of these [@Lind1979b; @Weig1995; @Weig2014]. Separating bald origins and subtype vegetation dynamics is key to preserving these dwindling ecosystems and conserving them for future generations [@Mora2013]. Within the mindset of a landscape ecologist, the point-of-view is all about differences in scale and size. Here, I examined changes to Round bald at the plot level scale to determine change in the vegetation community following a low-intensity ground fire disturbance in February 2022 which burned approximately 9.7 hectares. @Stok2022 examined the vegetation composition following 30 years of mowing management  on the balds of Carver's Gap [@Murd1986; @Hame1990].

### Seed bank

The soil seed bank is an ecologists term for the "potential community" layer. It is the prequel layer to the advanced regeneration layer that is currently growing on the forest floor. In this sense, ecologists look at the soil seed bank to predict what can grow in the next few growing seasons. Estimates of the soil seed bank are more accurate when using two methods - seedling emergence and seed extraction [@Pric2010; @Abel2013; and @Chiq2018]. The first plants the seed bank sample promptly following collection, while the second sieves the seeds from dirt and then planted individually.

### Woody Encroachment

The United States Forest Service (USFS) acquired some of the Southern Appalachian bald lands in the late 1920s after which, active management and general recreation ceased [@Lind1979b]. This led to shrub succession in the late 1930s and a management problem in the 1950s [@Lind1979; @Lind1980]. Despite the shrub succession on these balds, there is debate about whether to protect these areas or not. This is because the literature is unclear about bald origins - whether they are natural formations or human-engineered ecosystems. Following management cessation, the range of grass balds along the Southern Appalachian Mountains (SAMs) has decreased by *[find approx %]* since a study @Murd1986, who had surveyed round balds in the 1980s. A repeated survey of the balds of Carver's Gap in 2020 by @Stok2022, revealed a *[find % dec/inc]* in the cover of *Rubus allegheniensis* and *Rubus canadensis* (Rubus or blackbery) two primary native invasive species helping this grassy bald subtype to succeed into a heath bald subtype. On ideal balds, grass balds are dominated by grasses and sedge, while health balds are dominated by ericaceous shrubs. Without management, natural succession alters these balds from the grass to heath subtype.

### Managment

Bald management within the Southern Appalachian Mountains varies by managing agency and bald history, with most practices promoting mowing or grazing, with few instances of fire or clearing. When used, fire must be high intensity or high duration to provide a significant effect against woody encroachment [@Lind1980]. Germination requirements of the invasive genus Rubus include scarification - some damage to the seed has to occur for the seed to germinate [@Davi1998]. Fire can provide that damage and could possibly increase growth the following season. Sufficiently hot or lengthy burns have the potential to prevent the growth of blackberry, however post-burn analyses of the vegetation community indicates that the resulting community is not characteristic of grass balds [@Lind1980]. Likewise, prescribed burns are difficult to manage at such high elevations, soil moisture levels, and effects on rare and endemic species of historic balds.

### Objectives 

The objectives of this study are; 1. Quantify vegetation composition and the soil seed bank over the first and second growing seasons following the low intensity ground fire on Round Bald, and 2. Propose methods to improve management for conservation of these rare ecosystem subtypes. The general question is, how has the low-intensity ground fire affected vegetation dynamics and are there management practices that could be gleaned from this disturbance? I expect that there is little to no decrease in the cover of Rubus spp., likely there will be a slight increase in blackberry cover following slight scarification from the February 2022 ground fire.

### Round Bald 

Round bald - located on the borders of North Carolina and Tennessee along the Appalachian Trail about 20 miles North of Bakersville, NC - is experiencing woody encroachment from invasive species like *Rubus allegheniensis*, *Rubus canadensis*, *Vaccinium spp.*, *Rhododendrom spp.* and saplings from the surrounding spruce-fir forest. These species alter the bald by converting it from a grass bald into an ericaceous-heath bald. This could potentially extirpate a rare ecosystem subtype that provides panoramic vista views of the adjacent mountaintops and hosts a number of rare and endemic species, such as - Roan Lily, *Lilium grayi*. Nearly 40 years ago, @Murd1986 and @Hame1990 examined the vegetation community of Roan Mountain balds when the decision to protect these landscapes started to change. In 2020, following 30 years of mowing management, @Stok2022 re-surveyed plots from @Murd1986 and @Hame1990. In February of 2022, there was a low-intensity ground fire that burned for less than 6 hours and burned approximately 9.7 hectares of Round Bald. Roughly half of the plots that @Stok2022 surveyed on Round Bald along the first four transects were within the fire and the other half - along the same four transects - were outside of the fire boundary.

# METHODS

## 2022

### Study Site

Round bald is located in the Roan Mountain Massif of the Unaka Mountain range of the Southern Appalachian Mountains, between Carver's gap and Engine gap. The Appalachian Trail (AT) bisects the study site into North of the trail and South of the trail. The site itself is spread across Pisgah National Forest in North Carolina and Cherokee National Forest in Tennessee, at approximately 36° 06'N and 82° 60'W. In 2020, @Stok2022 surveyed the balds of Carver's Gap following a 30-year mowing management protocol from @Hame1990 and @Murd1986. They detailed the vegetation composition of the balds according to vegetation genera. Their data was entered into PCORD and produced a schematic of the vegetation communities across the balds of Carver's Gap [@PCORD]. In February 2022, a low-intensity ground fire burned roughly 9.7 hectares of aboveground vegetation and was quickly expunged before it could spread further. This provided an opportunity to examine the changes in vegetation composition following low-intensity ground fire over two sampling seasons in June of 2022 and 2023.

### Field Methods

In this study I sampled the first four transects reestablished by @Stok2022. I measured the percent coverage of vegetation using a 1-m^2 PVC quadrat divided into 100 equal sized squares, following @Stok2022. Each square was visually assigned by dominant vegetation genera to equal 100% coverage per plot of aboveground vegetation up to 1-meter in height. Using the data collection sheet from @Stok2022 and USFS botanist Gary Kauffman - which quantifies vegetation based on focal genera - a total of 226 plots along 12 transects were sampled in 2020, of these, 52 plots - along the first four transects were in the February 2022 fire - and another 47 plots - along the same transects - were untouched by the fire.

### Soil Seed Bank

To examine the effects of the fire on the seed bank, seed bank samples were collected in July 2022 and January 2023. In July 2022, approximately 200 grams  of soil was obtained from the top 5 cm of soil at six random sites in one of four treatments; over 50% Rubus/burned, over 50% Rubus/unburned, under 25% Rubus/burned, under 25% Rubus/unburned. The first - over 50% Rubus/burned - describes plots with greater than 50% cover of blackberry and burned from the February 2020 fire, followed by greater than 50% blackberry and unburned, less than 25% blackberry and burned, lastly, less than 25% blackberry and unburned. A total of 24 soil seed banks samples were taken, placed in tins, transferred to the greenhouse, then sown in 28x22 cm seedling trays filled with potting mix to 5 cm depth. An additional six trays were filled with unaltered potting mix which acted as greenhouse controls to rule out contamination. Trays were then randomly set in the greenhouse at ambient temperature and humidity and measured continuously with a Govee probe - which continuously measures temperature, percent relative humidity (%RH), dew point (DP), and vapor-pressure-deficit (VPD). As seedlings emerged they were identified, recorded, and removed. The seedlings that could not be identified were re-potted until identifiable following @Pric2010. Each month the trays were rotated in random order to rule out growth condition bias. In December of 2022, the soil sample trays were placed outside to simulate winter conditions and potentially germinate seeds in the seed bank over the next spring. 


## 2023

### Field Methods

In the summer of 2023 I plan to repeat surveys of the first four transects. In 2022, soil emergence was utilized for the sake of time and I plan to add a modified soil extraction method from @Pric2010; @Abel2013; and @Chiq2018 for the second sample set. These authors identify that both methods can provide insight into the potential vegetation community, but a combination of the two provides a more robust estimate of the state of the seed bank. A second set of soil seed bank samples were collected in January of 2023 following the same protocol as the first set. Except this time three samples were taken from each plot and a total of 108 samples were collected. 

### Soil Seed Bank

A total of 108 soil seed bank samples were collected from 36 sites from Round bald. One third of these samples were dried, weighed, and underwent seedling extraction. Each sample was sifted through 4000 micron mesh and then sifted with jewelers forceps to locate and count seeds in each sample - a total of 36 samples underwent seed extraction. Another third of the 108 samples were placed in one half of 10x20 inch seedling trays divided down the center. To accommodate for space in the greenhouse a total of 15 burned, 15 unburned, and 6 controls samples were sown into eighteen 10x20 inch seedling trays such that one half contained a sample that was burned and the other half had a sample that was unburnt.

### Analysis

For the time being, the data was recorded manually, then entered into excel to get a glimpse at the dynamics behind the low-intensity ground fire disturbance from January 2022. Based on cursory examination, blackberry is slightly increased in burned vs unburned. However, more analysis is needed. To do that I plan to follow the statistic tests that @Stok2022 had conducted in 2020. Once I fully understand their analysis, then I will be able to connect the data in 2020 to the data in 2022 and 2023. Otherwise, I will also be using analysis conducted by @Pric2010, @Monar), and @Murd1986.

### Expected Outcomes

I expect that Blackberry (Rubus) has slightly increased coverage following the February 2022 ground fire. I also expect that grasses and sedges are little to not-at-all different after the disturbance. If these statements are true, then implications for management are unchanged - fight fire as it arises and to not let the fire spread across the balds of Carver's Gap. More data will be gathered over March through August to better compare the dataset from @Stok2022, with the data that has been gathered for this study.

# References
