---
title: "Rough Draft"
author: "J. Ted Hillert"
date: "`r Sys.Date()`"
output:
  bookdown::word_document2:
    number_sections: false
    toc: yes

bibliography:
- aRticles.bib
   
csl: ecology.csl
---

\newpage

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo=FALSE,
                      message=FALSE,
                      warning=FALSE)


library(kableExtra)
library(latex2exp)
library(pandoc)
library(papaja)


papaja::r_refs(file="roughdraft.bib")

options(knitr.kable.NA="")


```

# Abstract

Carver's Gap lies on the border of Cherokee National Forest in Tennessee and Pisgah National Forest in North Carolina - a rare and unique ecosystem that hosts a high proportion of endemic flora. These balds are experiencing woody encroachment from the surrounding forest and from *Rubus* species that are threatening transition from a grass bald to a heath bald. The balds were surveyed in 2020 following 30 years of mowing management. Mowing was shown to reduce the spread of *Rubus* species and showed a positive effect on graminoid cover with frequent disturbance. However the results from the 2020 survey indicate that *Rubus* is present in dense patches and in the undergrowth across the balds. In February 2022, a low-intensity ground fire burned approximately 9.7 hectares of area on Round bald, the first bald on Carver's Gap. I surveyed vegetation, specifically *Rubus*, grasses, sedges, rhododendron, ferns, forbs, and moss, as well as rock and bare ground 1-meter square plots. This was done to examine the vegetation composition in the same manner as the 2020 survey. A total of 99 plots were measured along the first four transects established in 2020. Two sets of soil seed bank samples were taken in July of 2022 and January of 2023 to examine the effect of fire on the soil seed bank composition. The first underwent seedling emergence trial, while the latter underwent seedling emergence and seed extraction trials. Overall, fire had reduced the diversity of the vegetation composition and had a favorable effect on the growth of *Rubus* in burned and unburned plots. Ultimately the fire was too low intensity to cause a strong effect on the vegetation composition of the bald, however *Rubus* responded more favorably to fire than did grass. This represents a continued management concern of control of *Rubus* on the balds of Carver's Gap.

# Introduction

Upper montane treeless meadows - balds - host a high proportion of endemic species, such as Roan Lily (*Lilium grayi* S. Wats.) and Filmy Angelica (*Angelica triquinata* Michx.) and high ecotourism value [@Gers1970; @Murd1986; @Hame1990]. Balds are important for the ecosystem services they provide; they are sources of food and forage for fauna, medicinal value of flora, bioenergy production, soil erosion protection, carbon sequestration, water flow regulation, pest control, pollination, habitat for migratory species, gene pool protection, and cultural services for recreation and art [@Toka2017]. Balds are distributed along the southern Appalachian Mountain range through Virginia and globally with sites in Poland, Siberia, Ukraine, and Australia [@Toka2017]. Many balds are present above 1,400 meters in elevation and any bald can exist on a rock outcrop above 1,200 meters in elevation [@Gers1970]. Balds can be divided into subtype of grass balds, which are dominated by dense herbaceous vegetation and the presence of various forbs, and heath balds, which are dominated by evergreen ericaceous shrubs like *Kalmia latifolia* L. and *Rhododendron spp.*. Grass balds along the Southern Appalachian mountains are dominated by mountain oatgrass (*Danthonia compressa* Austin) and *Carex spp.* with various forbs present, such as Roan mountain goldenrod (*Solidago roanensis* Porter), three-toothed cinquefoil (*Sibbaldiopsis tridentata* Aiton) and false bugbane (*Trautvetteria caroliniensis* Walter) [@NCNHP; @Flem2001]. These meadows are often surrounded by forests of red spruce (*Picea rubens* Sarg.), Fraser fir (*Abies fraseri* (Pursh) Poir), beech (*Fagus grandifolia* Ehrh.), and yellow birch (*Betula alleghaniensis* Britton) [@Weig2013].

Some balds were cleared by Native Americans for hunting, pasturing livestock, and home and land use or by European settlers for timber and pasturing livestock in the spring and summer seasons [@Lind1979b]. Fire may have also been used as a means of maintaining open areas by European settlers [@Gers1970; @Lind1979b]. Other balds were driven by a climate-herbivore change in the landscape, making it a natural ecosystem. This climate-herbivore change was caused by Pleistocene glaciation opening up patches in the timberline that were subsequently grazed on by now extinct large herbivores and megafauna to maintain the open state [@Weig1995; @Weig2013].

Woody encroachment could potentially extirpate a rare ecosystem via expansion of *Rubus* to a dominating proportion on the balds of Carver's Gap. Nearly 40 years ago, @Murd1986 and @Hame1990 examined the vegetation community of Roan Mountain balds with the intent to protect these landscapes and reinstate management of these rare ecosystems. @Murd1986 found mowing with small application of fire to be sufficient in protecting against woody invasion. In 2020, @Stok2022 surveyed plots from @Hame1990 following 30 years of mowing management to assess the management practice. In February 2022, there was a low-intensity ground fire that burned approximately 9.7 hectares of Round Bald. Fifty-two plots that @Stok2022 surveyed on Round Bald were within the fire and another 47 plots were outside of the fire boundary (Figure 1).

The United States Forest Service (USFS) acquired some of the Southern Appalachian bald lands in the late 1920s, after which active management and general recreation ceased [@Lind1979b]. This led to shrub succession in the late 1930s and a management problem in the 1950s [@Lind1979b; @Lind1980]. Following management cessation, the range of grass balds along the Southern Appalachian Mountains has shifted in dominance to *Rubus spp.* until the study by @Murd1986, who suggested mowing management to control the spread of *Rubus*. A repeated survey of three balds of Carver's Gap in 2020 by @Stok2022 examined the vegetation of Round Bald, Jane Bald, and parts of Grassy Ridge Bald. The cover of *Rubus allegheniensis* (Porter) and *Rubus canadensis* (L.) (*Rubus*), two primary native invasive species are still present in dense patches on the balds and in the undergrowth across the balds. Grass balds have been experienced global habitat loss due to encroachment of the surrounding forests and woody vegetation. This decline of balds represents a widespread conservation and ecological restoration concern [@Cope2009]. Balds that are relatively stable are those that have been grazed or are maintained by frequent mowing and cutting [@Weig2013].

Bald management within the Southern Appalachian Mountains varies by managing agency and bald history, with most practices promoting mowing or grazing, and few instances of fire or timber clearing. When used, fire must be high intensity or high duration to provide a significant effect against woody encroachment, however post-burn analyses of the vegetation community indicates that the resulting community is not characteristic of grass balds [@Lind1980]. Track mowing has proven to be an appropriate management effort that shows positive effect against the spread of *Rubus* according to the study by @Murd1986. Since then, management of the balds of Carver's Gap is accomplished through track mowing on a yearly basis in the summer months before *Rubus* goes to seed.

The soil seed bank is a term for the potential community layer that can readily grow from the earth within the next few growing seasons. The seed bank includes all viable seeds that naturally occur on the landscape and are stored in the soil or on the soil surface [@Cson2007]. Seed banks dampen the effects of predictable environmental variation and variation from disturbances [@Temp1979]. Fire can positively or negatively affect a seeds ability to germinate due to smoke or the high temperatures experienced [@Gree2012]. To best quantify the seedbank a combination of seed extraction and seedling emergence provides the most robust estimate of the seed bank composition [@Abel2013; @Chiq2018]. Seed extraction removes the seeds from the soil to count their presence, while seedling emergence quantifies what grows from soil samples taken from the seedbank.

*Rubus*

Round bald is located along the borders of North Carolina and Tennessee on the Appalachian Trail, about 32 kilometers north of Bakersville, North Carolina and about 21 kilometers south of Roan Mountain, Tennessee. The site is largely south-facing with a slope of 13.5 degrees and an average soil depth of 14.2 ± 3.9 centimeters (personal data collection). Vegetation on this bald is dominated by *Danthonia spp.* and *Carex spp.* [@Flem1999]. Round Bald has been experiencing woody encroachment from invasive species like *R. allegheniensis*, *R. canadensis*, *Vaccinium spp.*, *Rhododendron spp.* and saplings from the surrounding spruce-fir forest. These species are threatening a shift from a grass bald subtype into a heath bald subtype.

I conducted this study to examine the effects of low-intensity ground fire the vegetation composition of Round Bald. I hypothesized that the fire was not of sufficient intensity to cause a major change in vegetation composition. The objectives were; 1. quantify vegetation composition over the 2020 and 2022 growing seasons following the low intensity ground fire on Round Bald, 2. examine the soil seed bank composition following the 2022 fire, and 3. Inform managing agencies about the state of the bald. How has the low-intensity ground fire affected vegetation dynamics in 2022 compared to 2020 from data provided by @Stok2022? What are the management implications that could be gleaned from this disturbance?

# Methods

### Study Site

Round Bald is located in the Roan Mountain Massif of the Unaka Mountain range of the Southern Appalachian Mountains, between Carver's Gap and Engine Gap. The Appalachian Trail (AT) bisects the study site into north and south sides of the trail. The site itself is spread across Pisgah National Forest in North Carolina and Cherokee National Forest in Tennessee, approximately 36.1065077° N and -82.1104007° W. The site is mesic due to high rainfall, frequent fog, and low temperatures. The site is also exposed to drying winds. In 2020, @Stok2022 surveyed the balds of Carver's Gap using methods from @Hame1990 to assess the effects of 30 years of management by mowing. The first four transects used in this study are identified in Figure 1. They quantified the vegetation composition of the balds according to vegetation functional type. In February 2022, a low-intensity ground fire burned roughly 9.7 hectares of aboveground vegetation and was quickly extinguished before it could spread further. The site has otherwise not been burned for several decades [@Murd1986].

### Field Methods

@Stok2022 surveyed Round Bald, Grassy Ridge Bald, and Jane Bald across 12 transects with 226 total plots. Plots were surveyed with a 1 x 0.5 m\^2 PVC quadrat divided into 50 equal sized squares and laid on the ground. Quadrats were flipped to survey a 1 m x 1 m plot divided into 100 10 cm x 10 cm squares. They assigned each square a dominant type of vegetation specifically *Rubus*, *Vaccinium*, *Rhododenron*, forbs, grasses, sedges, mosses, rock, or bare ground (bare ground was grouped as vegetation for the purposes of this study). I sampled the first four transects established by @Stok2022 wherein I quantified vegetation to the same functional types. These were determined to a single dominant vegetation and main functional species by USFS botanist Gary Kauffman (personal communication) as a method to efficiently survey the balds. I measured the percent coverage of vegetation using a 1-m\^2 PVC quadrat divided into 100 equal sized 10 cm x 10 cm squares. Each square was visually assigned by dominant vegetation functional type to equal 100% coverage per plot of aboveground vegetation up to 1-meter in height.

### Soil Seed Bank

To examine the effects of the fire on the seed bank, samples were collected in July 2022. Approximately 200 grams of soil were obtained from the top 5 cm of soil with the duff layer intact at twelve random plots along the each of the studied transects in either burned or unburned plots. A total of 24 soil seed bank samples were taken, placed in tins, transferred to the greenhouse, then sown in 28x22 cm seedling trays filled with Miracle Gro potting mix to 5 cm depth. An additional six trays were filled with unaltered potting mix which acted as greenhouse controls to rule out contamination. Trays were randomly placed in the greenhouse at ambient temperature and humidity. As seedlings emerged they were identified to genera, recorded, and removed. The seedlings that could not be identified were re-potted until identifiable following @Pric2010. Each month the trays were rotated in random order to equalize growing conditions. In December of 2022, the soil sample trays were placed outside to simulate winter conditions and cold stratify seeds in the seed bank over the next spring.

A modified seed extraction method from the second soil sample was added in 2023 following @Pric2010 @Abel2013; and @Chiq2018. These authors identify that both methods - seed extraction and seed germination - can provide insight into the potential vegetation community, but a combination of the two provides a more robust estimate of the state of the seed bank. There are drawbacks to both practices, with seedling emergence being time consuming and can give a over-exaggerated count of germinable seeds in the seed bank, especially because these seeds are grown in ideal conditions free from competition. Likewise, seed extraction can over-exaggerate the amount of viable seeds within the seed bank and is more labor intensive than seedling emergence. A second set of soil seed bank samples were collected in January of 2023 following the same protocol as the first set. This time, however, two samples were taken from each plot and a total of 72 samples were collected from 36 plots on Round bald half of which were from burned plots and the other half were from unburned plots. These samples were placed in the fridge at 4 °C until March 2023. In March these samples were removed from the fridge and placed in the greenhouse to thaw and dry. After which one half of the samples were sifted through 4000-micron mesh and then sifted through with jeweler's forceps to locate and count seeds - a total of 34 samples underwent seed extraction. Another 36 samples were placed in one half of 25x50 cm seedling trays divided down the center, such that each sample was in a 25x25 cm area and a depth of 5 cm. To accommodate for space in the greenhouse a total of 15 burned, 15 unburned were randomly selected sown alongside 6 controls samples into eighteen 25x50 cm seedling trays such that one half contained a sample that was burned and the other half had a sample that was unburned.

# Analysis

Differences between the 2020 and 2022 plant communities were analyzed using percent cover vegetation data and conducted in PC-ORD 7 [@PCORD7]. Nonmetric Multidimensional Scaling (NMDS) was used to visualize percent cover of vegetation for all plots in 2020 and all plots in 2022, each year individually, and for burned and unburned plots in 2022. NMDS analysis was performed on data for 2020 and 2022 on a matrix of 99 plots by 10 cover classes. Another NMDS was performed on the 52 burned plots by 8 cover classes and on the 47 unburned plots by 10 cover classes for data in 2022. Indicator Species Analysis was conducted to examine the abundance of each vegetation cover type across years. Multi-response permutation procedure (MRPP) was used to test whether vegetation composition differed between plots that were burned and plots that were unburned. Sorensen's distance was calculated from the percent cover data of the 99 total plots. Shannons diversity index (*H*) and Shannons evenness index (*J*) were calculated in Microsoft Excel to further examine the difference between vegetation composition between burned and unburned plots in 2022 [@msexcel]. Dominance curves for 2020 and 2022 were calculated in PC-ORD by multiplying the total abundance against the rank order of abundance, and were used to examine the distribution of vegetation by percent cover between years [@PCORD7]. A second set of dominance curves were created for unburned and burned samples in 2022 to examine the difference in vegetation composition caused by the fire.

Seed extraction data were averaged based on amount of seeds per 100g for burned and unburned plots. Soil seedbank emergence data were combined into one dataset and examined using the vegan package in R studio via PERManova between burned and unburned plots of each vegetation type that grew from sample trays [@rstudio; @vegan]. Shannon diversity was calculated using Microsoft Excel on soil sample emergence data to examine the diversity of species that grew from the seedbank in burned and unburned plots [@msexcel]. Shannon evenness index was also used to compare the composition and richness of burned and unburned samples. Dominance diversity curves were created for the burned and unburned seedbank samples to examine the difference in germination caused by the fire.

# Results

NMDS analysis of all plots in 2020 and all plots in 2022 vegetation plots indicated that these two were very similar and plots were concentrated in the center of the graph near *Rubus*, grass, and sedge cover types (Figure 2). The vegetation plots in 2020 were more strongly grouped near grass, *Rubus*, and sedge cover types with a stress value of 12.25 versus the less strongly grouped 2022 plots near grass, *Rubus*, and sedge cover types with a stress value of 11.10 (Figure 3). Further NMDS analysis of burned and unburned in 2022 shows a similar trend of strong grouping near grass, *Rubus*, and sedge in the unburned vegetation plots (Figure 4). Analysis with Shannon diversity index indicated the diversity in 2020 and 2022 were very similar: 1.69 versus 1.64, respectively (Table 1). Likewise Shannon evenness index indicated similar values in 2020 and 2022: 0.733 versus 0.714, respectively. Indicator species analysis showed an increase in *Rubus* and fern cover types between years as well as a slight decrease in relative frequency of grass (Table 2). Analysis of vegetation cover data by MRPP indicated significant differences between burned and unburned plots in both years - 2020 p = 0.00526 and 2022 p = 0.00554. In 2020 and 2022 the average within-group distance (observed delta) for unburned plots was greater in both years (Table 3).

In 2022 there were differences in Shannon diversity and evenness for unburned and burned plots - unburned plots had a diversity of 1.78 and an evenness of 0.775, while burned plots had a diversity of 1.36 and an evenness of 0.654. Dominance curves for all plots in 2020 versus 2022 indicated a marked increase in *Rubus* species and bare rock cover, and a marked decrease in *Rhododendron* and forb species (Figure 5). The 2022 dominance curve showed a greater number of cover types in unburned plots than in burned plots (Figure 6). The burned dominance curve, however, showed greater dominance of *Rubus*, fern, sedge, bare ground, and *Vaccinium* cover types and lesser dominance of moss, while the unburned showed presence of *Rhododendron* and forb cover, and a greater dominance of grass and moss cover.

Seed extraction data from the sifted soil samples showed a greater average number of seeds in burned samples versus unburned samples, 105.48 ± 42.6 seeds/100g versus 26.73 ± 17.4 seeds/100g - respectively. This result indicated that more seeds were in the seedbank of burned plots versus unburned plots. Shannon diversity scores indicated a different trend, the total diversity in the unburned samples was greater than the diversity in the burned samples, 1.051 versus 0.854 - respectively. Shannon evenness scores indicate a similar trend between unburned and burned samples, 0.758 versus 0.616 - respectively.

# Discussion

Results from the 2020 vs 2022 NMDS data indicated that vegetation is more concentrated around grass, *Rubus*, and forb species in 2020 and more dispersed in 2022. This finding indicates that the the effect fire has reduces the diversity of the landscape. A similar trend occurs in 2022 between burned and unburned vegetation plots, here vegetation is more dispersed in burned plots versus more concentrated around grass, *Rubus*, and sedge species in unburned plots. This finding also indicated a shift in vegetation composition due to the 2022 fire. Results from MRPP between burned and unburned plots showed differences both years although there was little difference overall. Thus fire had little overall effect on vegetation composition across the landscape. These data are in support of the hypothesis that the fire would have little effect on the bald. This is likely due to the fact that the fire did not burn for a long enough period of time nor did it reach a high enough temperature to cause a strong lasting effect.

Further support for this finding comes from Shannons indices, which showed that the 2020 and 2022 vegetation compositions were very similar in diversity and evenness. However, in 2022 alone, the diversity in the unburned plots was greater than the diversity in the burned plots, with burned plots being less even than unburned plots. The dominance curves for 2020 and 2022 showed a similar trend with more evenness in 2020 than in 2022. The dominance curve for 2022 matches up with the finding from Shannons diversity and evenness indices, with more evenness and diversity in the unburned plots. There was greater dominance of *Rubus*, grass, fern, sedge, and bare ground cover types in burned plots versus greater proportion of grass, *Rubus*, fern, moss, bare ground, *Rhododendron*, sedge, and rock cover types in unburned plots. *Rubus* outcompeted all other cover types in burned plots, while grass outcompeted all other cover types in unburned plots. Between years there was no difference in composition just a difference in proportion of species in plots. These findings indicated that *Rubus* responded favorably to the fire and that fire could prevent the recovery of this grass bald through the expansion of *Rubus spp.* to a greater proportion of the landscape.

Soil seed extraction and germination samples were collected all together as one sample composed of the duff layer and the underlying soil. In the soil extraction trial, a greater number of seeds were extracted from burned versus unburned soil samples indicating the duff layer of unburned plots acts as a filter that prevents seeds from entering the seedbank. Only one type of seed was identified, belonging to *Rubus* species, all other seeds were to small to identify or too rare to be a major part of the soil extraction samples. Results from the seedbank emergence trial showed greater diversity in the unburned plots suggesting that fire has a reducing effect on diversity and evenness of the seedbank. Likewise it is possible that fire has a reducing effect on the abundance of *Rubus* species on the landscape. Further experimentation with fire is necessary to draw conclusions on the effects of fire. It is important to note that data for the emergence trial were drawn from a small dataset of 33 observations therefore it is likely that these results are not indicative of the true state of the seedbank.

Fire suppression activities in the 1950's virtually eliminated fire as an ecological process on balds [@Broc2002]. Prescribed burns were suggested as an appropriate management regime as it has been used on some balds to maintain openness of the bald by European settlers and native people [@Gers1970; @Bard1978]. However *Rubus* showed a favorable response to fire by increasing in abundance in burned plots, therefore it is unlikely that fire will be reintroduced as a management practice on Round bald (pers. comm. Gary Kauffman USFS) and therefore some form of management on patches of *Rubus* is necessary. Hand pulling of aboveground vegetation is ineffective as *Rubus* is able to regrow from the smallest fragmented root stock [@Davi1998], likewise it would be extremely labor intensive. Herbicide treatment is dangerous because of the leeching effect of chemical to the surrounding vegetation causing unknown effects and could ultimately do more harm than good [@Davi1998]. Grazing was once a popular practice on balds, especially due to its purported reason for balds existence. However, it has been reported that grazing was attempted on Round bald and other balds but the non-selectivity of grazers caused the practice to be discontinued [@Stok2022] due to negative effects on rare flora. It is therefore likely that track mowing is the most convenient, selective, and safe method for maintaining this bald. However, considering the presence of *Rubus* despite many years of mowing being the prime management tool on these balds, it is likely pertinent to increase the amount of mowing to see any future effects on woody invasion. I suggest mowing a second time earlier in the year before grasses are far above the ground and when *Rubus* species are still canes and a second mow later in the season before *Rubus* goes to fruit. This would cause the plants to use up more of the energy in their root stores and prevent seeds from making it into the seedbank later in the season.

The objectives of this study were to examine how the 2022 low intensity ground fire affected the vegetation community compared to the 2020 vegetation community. They found that grass and grass/*Rubus* to be the two most dominant vegetation community types on Round bald. Their data indicate successful management of *Rubus* between the study in 1986 and 2020, however, they also indicate that *Rubus* is still present in thick patches and in the undergrowth across the bald. Mowing has been shown to be an appropriate management method for the controlling the spread of *Rubus* on the grass balds of Carver's Gap [@Murd1986]. In the absence of fire as a management tool, a second application of mowing earlier in the year should to be considered as a means of reducing energy stores of invasive plants. Continued monitoring of the vegetation composition of the balds through yearly surveys is crucial to the persistence of these balds as grass balds. Future research would be key to maintaining the diversity and aesthetic value of the flora of this grass bald and other balds. Continued management is key to protecting grass balds and their conservation and preservation is essential for the persistence of these dwindling ecosystems, the rare and endemic flora that they host, the ecosystem services they provide, and their aesthetic value for ecotourism.

\newpage

# References
